USE tempdb
GO

CREATE TABLE tblOrders  
(
  ID INT NOT NULL PRIMARY KEY,
  TitleTag NVARCHAR(100) NOT NULL,
  Measure INT NOT NULL DEFAULT 0
)


INSERT INTO tblOrders VALUES
  (111, 'Comedy', 1),  (112, 'NEGOT', 1),  
  (113, 'BUSINESS', 1)


SELECT * FROM tblOrders				-- 3 ROWS

SET DEADLOCK_PRIORITY LOW			-- THIS MEANS, THE CURRENT SESSION CAN BE THE DEADLOCK VICTIM INCASE OF ANY DEADLOCK.


BEGIN TRAN T1
UPDATE tblOrders SET Measure = 100
-- NOW, EXECUTE THE ENTIRE TRANSACTION T2

UPDATE tblInventory SET Measure = 10
