
-- BACKUP AUDITS

SELECT * FROM MSDB.DBO.backupset			-- CONTAINS AN ENTRY FOR EVERY BACKUP WE PERFORM ON THE SERVER

SELECT * FROM MSDB.DBO.backupfile			-- CONTAINS AN ENTRY FOR EVERY DATA FILE OR LOG FILE INVOVLED IN THE BACKUP

SELECT * FROM MSDB.DBO.backupfilegroup		-- CONTAINS AN ENTRY FOR EVERY FILEGROUP INVOVLED IN THE BACKUP

SELECT * FROM MSDB.DBO.backupmediaset		-- CONTAINS AN ENTRY FOR EVERY UNIQUE BACKUP (FILE) LOCATION

SELECT * FROM MSDB.DBO.backupmediafamily	-- CONTAINS AN ENTRY FOR EVERY BACKUP LOCATION & ITS PHYSICAL PATH


-- HOW TO USE ABOVE BACKUP AUDIT TABLES?
-- EXAMPLE: HOW TO AUDIT FOR LATEST FULL BACKUP?
SELECT TOP 1 B.DATABASE_NAME, B.TYPE, B.backup_finish_date , M.physical_device_name AS BACKUP_LOCATION
FROM MSDB.DBO.backupset AS B
INNER JOIN
MSDB.DBO.backupmediafamily AS M
ON
B.media_set_id = M.media_set_id
WHERE B.TYPE = 'D' AND B.DATABASE_NAME = 'PRODUCT_DATABASE'
ORDER BY B.backup_finish_date DESC 



-- EXAMPLE: HOW TO AUDIT FOR LATEST DIFFERENTIAL BACKUP?
SELECT TOP 1 B.DATABASE_NAME, B.TYPE, B.backup_finish_date , M.physical_device_name AS BACKUP_LOCATION
FROM MSDB.DBO.backupset AS B
INNER JOIN
MSDB.DBO.backupmediafamily AS M
ON
B.media_set_id = M.media_set_id
WHERE B.TYPE = 'I' AND B.DATABASE_NAME = 'PRODUCT_DATABASE'
ORDER BY B.backup_finish_date DESC


-- EXAMPLE: HOW TO AUDIT FOR LOG BACKUPS AFTER A SPECIFIC DATE?
SELECT TOP 1 B.DATABASE_NAME, B.TYPE, B.backup_finish_date , M.physical_device_name AS BACKUP_LOCATION
FROM MSDB.DBO.backupset AS B
INNER JOIN
MSDB.DBO.backupmediafamily AS M
ON
B.media_set_id = M.media_set_id
WHERE B.TYPE = 'L' AND B.DATABASE_NAME = 'PRODUCT_DATABASE'
AND
backup_finish_date > '2018-10-23 18:19:16.000'
ORDER BY B.backup_finish_date DESC  