/*
RECOVERY MODELS	:  A PROPERTY USING WHICH WE CAN CONTROL THE LEVEL OF DATABASE LOGGING OPERATIONS.

TYPES OF RECOVERY MODELS:
			***	1. FULL RECOVERY MODEL			- EVERY TRANSACTION METADATA + ACTUAL DATA IS AUDITTED
				2. SIMPLE RECOVERY MODEL		- EVERY TRANSACTION METADATA AUDITTED
				3. BULK LOGGED RECOVERY MODEL	- EVERY DETAIL IS COMPLETELY LOGGED EXCEPT BULK OPERATIONS.
												  THESE BULK OPERATIONS ARE MINIMALLY LOGGED. 

				DEFAULT RECOVERY MODEL IS "FULL".

				LOG BACKUPS ARE NOT POSSIBLE IN SIMPLE RECOVERY MODEL.
				IN SIMPLE RECOVERY MODEL, DATABASE REQUIRES LESSER STORAGE SPACE. 

** IT IS RECOMMENDED TO PERFORM A NON BASE FULL BACKUP BEFORE CHANGING THE RECOVERY MODEL OF THE DATABASE.
** TRANSACTION METADATA   ::  TRANSACTION TIMESTAMP, STATUS, KIND OF OPERATION, SESSION ID, LOGIN NAME....
*/
						
ALTER DATABASE [PRODUCT_DATABASE] SET RECOVERY FULL 
ALTER DATABASE [PRODUCT_DATABASE] SET RECOVERY SIMPLE 
ALTER DATABASE [PRODUCT_DATABASE] SET RECOVERY BULK_LOGGED  