USE MASTER 
GO
-- STEP 1: REPORT FRAGMENTATION FOR ALL INDEXES ACROSS ALL DATABASES?
SELECT * FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(null, null, null, null, NULL)

-- STEP 2: REPORT HEAVILY FRAGMENTED INDEXES ACROSS ALL DATABASES?
SELECT * FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(null, null, null, null, NULL)
WHERE avg_fragmentation_in_percent >  80

-- STEP 3: HOW TO FIND FRAGMENTAITON DETAILS FOR A GIVEN DATABASE & OBJECT?
SELECT * FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(6, 309576141, 1, 1, NULL)

-- STEP 4: IDENTIFY DATABASE NAME
SELECT DB_NAME(6)  -- SSASSBS

-- STEP 5: CONNECT TO ABOVE DATABASE, IDENTIFY THE TABLE NAME
USE SSASSBS
GO
SELECT OBJECT_NAME(309576141)  -- FactInternetSales  

-- STEP 7: IDENTIFY THE INDEX NAME FOR ABOVE TABLE
SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = 309576141  -- PK_FactInternetSales_SalesOrderNumber_SalesOrderLineNumber
 

-- STEP 8: FOR HIGHER FRAGMENTATION VALUES, WE NEED TO REBUILD THE INDEX
ALTER INDEX PK_FactInternetSales_SalesOrderNumber_SalesOrderLineNumber
ON FactInternetSales
REBUILD 

-- OR

-- STEP 8: FOR MODERATE FRAGMENTATION VALUES, WE NEED TO REORGANISE THE INDEX
ALTER INDEX PK_FactInternetSales_SalesOrderNumber_SalesOrderLineNumber
ON FactInternetSales
REORGANIZE 


-- STEP 9: VERIFY THE FRAGMENTATION LEVELS AFTER INDEX REBUILD OR REORGANIZE
SELECT * FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(6, 309576141, 1, 1, NULL)
