CREATE DATABASE DB1
GO
USE DB1 
GO
CREATE TABLE TABLE1  ( COL1 INT, COL2 INT )
INSERT INTO TABLE1 VALUES (1,1), (2,2), (3,3), (4,4)



SELECT * FROM TABLE1								-- 1 PART NAMING CONVENTION
SELECT * FROM DBO.TABLE1							-- 2 PART NAMING CONVENTION
SELECT * FROM DB1.DBO.TABLE1						-- 3 PART NAMING CONVENTION
SELECT * FROM [SQLSCHOOL\SQLSCHOOL1].DB1.DBO.TABLE1 -- 4 PART NAMING CONVENTION

SELECT @@SERVERNAME				-- TO KNOW THE SERVER NAME
SELECT * FROM [SQLSCHOOL\SQLSCHOOL2].DB2.DBO.TABLE2  -- ERROR

/*
CREATE LINKED SERVER : 
From 1st server > Server Objects > New > Linked Server >  Specify 2nd servername.
	Security : Option #3, Server Options: Data Access (True), RPC (True), RPC Out (True)
	RPC : REMOTE PROCEDURE CALL   [RPC:  Reads,   RPC Out : Write]
	
TEST CONECTION TO THE LINKED SERVER.
Right click above created linked server > Test Connection
*/

-- TEST THE REMOTE QUERY EXECUTION: 
SELECT * FROM [SQLSCHOOL\SQLSCHOOL2].DB2.DBO.TABLE2   -- NO ERROR


-- REMOTE JOINS:
SELECT * FROM [SQLSCHOOL\SQLSCHOOL1].DB1.DBO.TABLE1 AS A
CROSS JOIN 
[SQLSCHOOL\SQLSCHOOL2].DB2.DBO.TABLE2  AS B