CREATE DATABASE DB2
GO
USE DB2
GO
CREATE TABLE TABLE2  ( COL1 INT, COL2 INT )
INSERT INTO TABLE2 VALUES (1,1), (2,2), (3,3), (4,4)

SELECT * FROM TABLE2								-- 1 PART NAMING CONVENTION
SELECT * FROM DBO.TABLE2							-- 2 PART NAMING CONVENTION
SELECT * FROM DB2.DBO.TABLE2						-- 3 PART NAMING CONVENTION
SELECT * FROM [SQLSCHOOL\SQLSCHOOL2].DB2.DBO.TABLE2 -- 4 PART NAMING CONVENTION
