
SELECT * FROM SYS.PARTITIONS WHERE OBJECT_ID = OBJECT_ID('sales_data')   


SELECT * FROM [dbo].[CUSTOMERS_DATA]


ALTER TABLE SALES_DATA REBUILD PARTITION = 1 WITH ( DATA_COMPRESSION  = ROW)
SELECT * FROM SYS.PARTITIONS WHERE OBJECT_ID = OBJECT_ID('sales_data')   


ALTER TABLE SALES_DATA REBUILD PARTITION = 1 WITH ( DATA_COMPRESSION  = PAGE)
SELECT * FROM SYS.PARTITIONS WHERE OBJECT_ID = OBJECT_ID('sales_data')   


ALTER TABLE SALES_DATA REBUILD PARTITION = 1 WITH ( DATA_COMPRESSION  = NONE)
SELECT * FROM SYS.PARTITIONS WHERE OBJECT_ID = OBJECT_ID('sales_data')   


ALTER TABLE SALES_DATA REBUILD WITH ( DATA_COMPRESSION  = ROW)
SELECT * FROM SYS.PARTITIONS WHERE OBJECT_ID = OBJECT_ID('sales_data')   