CREATE DATABASE DB_BASIC_OBJECTS

USE DB_BASIC_OBJECTS

CREATE TABLE EMP_INFO			
(
EMP_ID		INT PRIMARY KEY,	
EMP_FNAME	VARCHAR (30),	 
EMP_CNTRY	CHAR(50), 
EMP_SAL		BIGINT		
)	

					
INSERT 	 EMP_INFO VALUES  (1001, 'AMIN',  'CANADA', 45678) , ('1002', 'JOHN', 'CANADA', 643643)	
INSERT   EMP_INFO VALUES   (1003, 'SAI', 'INDIA', 36363), (1004, 'SAISHA', 'INDIA',20000)		
INSERT   EMP_INFO VALUES   (1005, 'SAISH', 'INDIA', 43643),   (1006, 'ADAM', 'USA', NULL)   

SELECT * FROM EMP_INFO

-- EXAMPLE 1:  USER DEFINED VIEWS 
CREATE VIEW VW_INDIA_EMPLOYEES
AS
SELECT * FROM EMP_INFO WHERE EMP_CNTRY = 'INDIA'

-- HOW TO ACCESS ABOVE VIEW
SELECT * FROM VW_INDIA_EMPLOYEES

-- IMPORTANT SYSTEM VIEWS : FOR METADATA [SYSTEM INFORMATION] AUDITS
-- THESE SYSTEM VIEWS ARE AUTO CREATED DURING DATABASE CREATION ITSELF. IN PRIMARY DATA FILE (mdf).

SELECT * FROM SYS.DATABASES		-- TO REPORT LIST OF ALL DATABASES IN THE SERVER
SELECT * FROM SYS.SCHEMAS		-- TO REPORT LIST OF ALL SCHEMAS IN THE DATABASE
SELECT * FROM SYS.TABLES		-- TO REPORT LIST OF ALL TABLES IN THE DATABASE
SELECT * FROM SYS.INDEXES		-- TO REPORT LIST OF ALL INDEXES IN THE DATABASE
SELECT * FROM SYS.OBJECTS		-- TO REPORT LIST OF ALL OBJECTS (SCHEMAS, TABLES, KEYS, INDEXES, VIEWS..) IN DATABASE

SELECT * FROM INFORMATION_SCHEMA.COLUMNS	-- TO REPORT LIST OF ALL COLUMNS IN THE TABLES & VIEWS WITHIN THE DATABASE




-- EXAMPLE 2:  USER DEFINED FUNCTIONS 
-- REQUIREMENT : GIVEN A COUNTRY VALUE, WE NEED TO REPORT LIST OF ALL EMPLOYEES IN THAT COUNTRY?
CREATE FUNCTION FN_REPORT_EMPLOYEES (@Country varchar(30))			-- @Country is a PARAMETER
RETURNS table
AS
RETURN ( SELECT * FROM EMP_INFO WHERE EMP_CNTRY = @Country)

-- HOW TO ACCESS OR EXECUTE OR TEST ABOVE FUNCTION
SELECT * FROM FN_REPORT_EMPLOYEES('INDIA') 
SELECT * FROM FN_REPORT_EMPLOYEES('USA') 
SELECT * FROM FN_REPORT_EMPLOYEES('CANADA') 
SELECT * FROM DBO.FN_REPORT_EMPLOYEES('CANADA') 

-- IMPORTANT SYSTEM FUNCTIONS : FOR METADATA [SYSTEM INFORMATION] AUDITS
SELECT DB_NAME()			-- REPORTS CURRENTLY CONNECTED DATABASE NAME
SELECT DB_ID()				-- REPORTS CURRENTLY CONNECTED DATABASE ID
SELECT DB_NAME(7)			-- REPORTS DATABASE NAME FOR A GIVEN DATABASE ID
SELECT DB_ID('DB_BASIC_OBJECTS') 	-- REPORTS DATABASE ID FOR A GIVEN DATABASE NAME
SELECT OBJECT_ID('EMP_INFO') 	-- REPORTS OBJECT ID FOR A GIVEN OBJECT NAME
SELECT OBJECT_NAME(581577110) 	-- REPORTS OBJECT NAME FOR A GIVEN OBJECT ID
SELECT GETDATE()			-- REPORTS TODAY'S DATE & TIME
SELECT @@SERVERNAME			-- REPORTS THE CURRENTLY CONNECTED SERVER NAME
SELECT @@VERSION			-- REPORTS VERSION, EDITION OF THE CONNECTED SQL SERVER




-- EXAMPLE 3:  USER DEFINED PROCEDURES (STORED PROCEDURES)
CREATE PROCEDURE SP_REPORT_EMPLOYEES (@Country varchar(30))	 -- @Country is a PARAMETER
AS
SELECT * FROM EMP_INFO WHERE EMP_CNTRY = @Country

-- UNLIKE FUNCTIONS, THE STORED PROCEDURES [SPs or SPROCs or PROCs] ARE PRECOMPILED, PRE-OPTIMIZED.
-- MEANS, THE QUERY SPECIFIED IN THE PROCEDURE DEFINITION IS COMPILED AND STORED IN THE DATABASE. 
-- ALSO, THE EXECUTION PLAN IS GENERATED AND STORED BY QUERY OPTIMIZER IN THE DATABASE FOR READY USAGE.

-- TO ACCESS ABOVE STORED PROCEDURE
EXEC SP_REPORT_EMPLOYEES 'INDIA'
EXECUTE SP_REPORT_EMPLOYEES 'CANADA'

-- IMPORTANT SYSTEM PROCEDURES : FOR METADATA [SYSTEM INFORMATION] AUDITS
EXEC SP_HELPDB				-- TO REPORT LIST OF ALL DATABASES IN THE SERVER
EXEC SP_HELP				 -- TO REPORT LIST OF ALL OBJECTS IN THE DATABASE
EXEC SP_HELP 'EMP_INFO'  		-- TO REPORT DEFINITION OF THE GIVEN OBJECT [TABLE]
EXEC SP_HELPINDEX 'EMP_INFO'	-- TO REPORT ALL INDEXES OF THE GIVEN TABLE
EXEC SP_PKEYS	'EMP_INFO'		-- TO REPORT PRIMARY KEY INFORMATION OF THE GIVEN TABLE
EXEC SP_DEPENDS 'EMP_INFO'		-- TO REPORT ALL DEPENDANCIES ON THE GIVEN TABLE
EXEC SP_RENAME 'EMP_INFO', 'NEW_TABLE_NAME'  		-- RENAME A TABLE OR DB OBJECT
EXEC SP_RECOMPILE	'SP_REPORT_EMPLOYEES'    		-- RECOMPILE THE QUERY. REGENERATE A NEW MACHINE CODE FOR THE STORED PROCEDURE DEFINITION
EXEC SP_HELPTEXT	'SP_REPORT_EMPLOYEES'    		-- REPORT DEFINITION OF PROCEDURE 



