/*
SCHEMAS  : DATABASE OBJECTS USED TO GROUP MULTIPLE TABLES [OR VIEWS, PROCEDURES, ETC..]
PURPOSE  : USED FOR EASY DATA ACCESS AND EASY SECURITY MANAGEMENT
DEFAULT SCHEMA IS "DBO". MEANS: " DATABASE OWNER "
*/

USE PRODUCT_STORE_DB

-- ITEM #1. HOW TO CREATE SCHEMAS IN A DATABASE ?
CREATE SCHEMA SCHEMA1
GO
CREATE SCHEMA SCHEMA2


-- ITEM #2. HOW TO CREATE THE TABLES USING THE SCHEMAS ?
CREATE TABLE SCHEMA1.TABLE1 (COL1 INT, COL2 INT, COL3 DATE)
CREATE TABLE SCHEMA1.TABLE2 (COL1 INT, COL2 INT)


-- ITEM #3: HOW TO STORE DATA INTO THE ABOVE TABLES ?
INSERT INTO SCHEMA1.TABLE1 VALUES (1,1, '2018-12-31'), (2,2, GETDATE()), (3,3,'2018/12/31')


-- ITEM #4: HOW TO REPORT DATA FROM ABOVE TABLES ?
SELECT * FROM SCHEMA1.TABLE1


-- ITEM #5: HOW TO MOVE (MIGRATE) A TABLE FROM ONE SCHEMA TO ANOTHER ?
ALTER SCHEMA SCHEMA2 TRANSFER SCHEMA1.TABLE1


-- ITEM #6: HOW TO TEST THE ABOVE TABLE TRANSFER ?
SELECT * FROM SCHEMA2.TABLE1								-- 2 PART NAMING CONVENTION

SELECT * FROM [PRODUCT_STORE_DB].SCHEMA2.TABLE1				-- 3 PART NAMING CONVENTION

SELECT * FROM [SQLSCHOOL].[PRODUCT_STORE_DB].SCHEMA2.TABLE1 -- 4 PART NAMING CONVENTION


USE MASTER 
SELECT * FROM [PRODUCT_STORE_DB].SCHEMA2.TABLE1	
SELECT * FROM [SQLSCHOOL].[PRODUCT_STORE_DB].SCHEMA2.TABLE1


-- SYNONYM : A PERMENANT ALTERNATE NAME TO ANY OBJECT [EX: TABLE]
CREATE SYNONYM TBL1 FOR [PRODUCT_STORE_DB].SCHEMA2.TABLE1	
SELECT * FROM TBL1







SELECT * FROM #TABLE1			-- ERROR. REASON : THIS IS A LOCAL TEMPORARY TABLE. ONLY AT SESSION LEVEL. 

SELECT * FROM ##TABLE2			-- THIS IS A GLOBAL TEMPORARY TABLE. ACCESSIBLE ACROSS SESSIONS. NO ERROR



-- SCHEMAS					-- SYNONYMS					-- TEMPORARY TABLES