CREATE DATABASE StarlinersFc

USE StarlinersFc

CREATE TABLE PlayerInfo
(
PlayerId         INTEGER,        -- THIS COLUMN STORES DIGITS: 0, -10, 99 ...
PlayerName       CHARACTER(50),
PlayerNumber      INT,           -- THIS COLUMN STORES DIGITS: 0, -10, 99 ...
Size              VARCHAR(10),
Age               INT,           -- THIS COLUMN STORES DIGITS: 0, -10, 99 ...
Height            CHAR,           -- THIS COLUMN STORES DIGITS: 0, -10, 99 ...
)

SELECT * FROM PlayerInfo


-- CHAR : TO STORE STATIC, FIXED VALUES.                   EX: USERNAME
-- VARCHAR : TO STORE DYNAMIC, CHNAGING (VARYING) VALUES.  EX: PASSWORD
UPDATE TABLE PlayerInfo

INSERT 	INTO    PlayerInfo VALUES (1, 'MICHAEL', 10, 'S', 23, '1.75')
INSERT          PlayerInfo VALUES (2, 'YOHANNES', 15 , 'M', 23, '1.82')
INSERT          PlayerInfo VALUES  (3, 'SIMON', 23, 'S', 20, '1.70')
INSERT   INTO   PlayerInfo VALUES (4, 'ABDUL', 2, 'M', 25, '1.80')
INSERT   INTO    PlayerInfo VALUES (5, 'FREDO', 11, 'M', 23, '1.80'),  (6, 'FLAV', 6, 'L', 25, '1.85')


-- QUERY 5: HOW TO REPORT ABOVE INSERTED DATA IN THE TABLE ?
SELECT * FROM PlayerInfo              -- * MEANS TO REPORT TALL COLUMNS IN A TABLE

-- QUERY 6: HOW TO REPORT ALL EMPLOYEES FROM CANADA ?
SELECT  *  FROM PlayerInfo WHERE Size = 'S'  

-- QUERY 7: HOW TO REPORT ALL EMPLOYEES FROM USA OR CANADA ?
SELECT  *  FROM PlayerInfo WHERE Age = '23'  OR  PlayerName = 'MICHAEL'

-- QUERY 8: HOW TO REPORT ALL EMPLOYEES FROM USA OR CANADA ?
SELECT  *  FROM PlayerInfo WHERE Height  IN ( '1','2')

-- QUERY 9: HOW TO REPORT ALL EMPLOYEES EXCEPT FROM USA OR CANADA ?
SELECT  *  FROM PlayerInfo WHERE PlayerId NOT IN ( '1','2')

-- QUERY 12: HOW TO REPORT ALL EMPLOYEES WHOSE FIRST NAME STARTS WITH LETTER 'J'?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EmployeeName  LIKE 'J%'   

-- QUERY 13: HOW TO REPORT ALL EMPLOYEES WHOSE FIRST NAME NOT START WITH LETTER 'J'?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EmployeeName NOT LIKE 'J%'   

 -- QUERY 14: HOW TO REPORT ALL EMPLOYEES WITH ASCENDING ORDER OF SALARIES? 
SELECT  *  FROM EMPLOYEE_INFO ORDER BY EmployeeSalary  ASC

-- QUERY 15: HOW TO REPORT ALL EMPLOYEES WITH DESCENDING ORDER OF SALARIES? 
SELECT  *  FROM EMPLOYEE_INFO ORDER BY EmployeeSalary   DESC


-- QUERY 16: HOW TO REPORT TOP 2 EMPLOYEES WITH HIGHEST SALARY ?
SELECT  TOP 2 *  FROM EMPLOYEE_INFO ORDER BY EmployeeSalary DESC



/* 
CREATE : TO CREATE OR DEFINE NEW DATABASE OR TABLE
USE : TO CONNECT TO A SPECIFIC DATABASE

INSERT : TO STORE DATA INTO TABLE 
SELECT : TO REPORT DATA FROM TABLE
    WHERE: TO SPECIFY CONDITIONS ON TABLE DATA

		   IN: TO CHECK FOR GIVEN VALUES AND REPORT MATCHING ITEMS
		   NOT IN: TO CHECK FOR GIVEN VALUES AND REPORT NON MATCH ITEMS

		   BETWEEN: TO CHECK FOR GIVEN RANGE OF VALUES
		   NOT BETWEEN: TO CHECK FOR DATA OUTSIDE THE GIVEN RANGE OF VALUES

		   LIKE:       TO SEARCH FOR TEXT DATA BASED ON THAT MATCHES WITH THE GIVEN PATTERN.
		               EX: SEARCH FOR ALL EMPLOYEES WHOESE NAME STARTS WITH THE LETTER "J"
		   NOT LIKE:   TO SEARCH FOR TEXT DATA BASED ON THAT DOESN'T MATCH WITH THE GIVEN PATTERN.
		               EX: SEARCH FOR ALL EMPLOYEES WHOSE NAME DOESN'T START WITH THE LETTER "J"

	ORDER BY : USED TO SORT (ARRANGE) THE DATA
	       ASC :    TO SORT THE DATA IN ASCENDING ORDER.  LOW TO HIGH. DEFAULT.
		   DESC:    TO SORT THE DATA IN DESCENDING ORDER. HIGH TO LOW 

	TOP
	MAX(), MIN()

	SUB QUERY
*/

-- REQUIREMENT : HOW TO REPORT LIST OF ALL PLAYERS THAT HAVE HIGHEST AGE?

SELECT MAX(Age) FROM PlayerInfo

SELECT * FROM PlayerInfo WHERE Age = 25

SELECT * FROM PlayerInfo WHERE Age = (SELECT MAX(Age) FROM PlayerInfo)

SELECT * FROM PlayerInfo WHERE Age = (SELECT MIN(Age) FROM PlayerInfo)



ALTER TABLE PlayerInfo ADD   [PlayerCountry]   VARCHAR(30)
SELECT * FROM PlayerInfo

ALTER TABLE PlayerInfo ADD   [PlayerSalary]   VARCHAR(30)
SELECT * FROM PlayerInfo

-- QUERY 19:  HOW TO MODIFY THE EXISTING DATA IN A TABLE? EX: HOW TO MODIFY SALARIES?
UPDATE PlayerInfo SET PlayerSalary  = 10000 WHERE PlayerCountry = 'CANADA' 
SELECT * FROM PlayerInfo


-- QUERY 20:   HOW TO REMOVE THE LIST OF ALL EMPLOYEES FROM TABLE  [Logged in ldf FILE]
DELETE FROM PlayerInfo WHERE PlayerCountry = 'CANADA' 
SELECT * FROM PlayerInfo

DELETE FROM PlayerInfo			-- REMOVES ALL DATA FROM TABLE ROW BY ROW
SELECT * FROM PlayerInfo

-- QUERY 21:   HOW TO REMOVE THE LIST OF ALL EMPLOYEES FROM TABLE  [Not Logged in ldf FILE] 
TRUNCATE TABLE PlayerInfo		-- REMOVES ALL ROWS FROM THE TABLE AT ONCE 


-- QUERY 22:   	HOW TO ADD NEW COLUMN TO EXISTING TABLE?
ALTER TABLE PlayerInfo ADD   [EMP  LOCATION]   VARCHAR(30)
SELECT * FROM PlayerInfo

-- QUERY 23:	HOW TO MODIFY STRUCTURE OF EXISING COLUMN IN EXISTING TABLE?
ALTER TABLE PlayerInfo ALTER COLUMN   [EMP  LOCATION]   VARCHAR(3000)


-- QUERY 24:	HOW TO REMOVE AN EXISING COLUMN FROM THE TABLE?
ALTER TABLE PlayerInfo DROP COLUMN    [EMP  LOCATION]
SELECT * FROM PlayerInfo

-- QUERY 25:	HOW TO REMOVE THE TABLE FROM DATABASE?     -- OPPOSITE OF CREATE TABLE STATEMENT 
DROP TABLE PlayerInfo


-- DIFFERENCE BETWEEN DROP AND DELETE?
    -- DELETE  :  TO REMOVE THE CONTENT INSIDE THE TABLE
	-- DROP    : TO REMOVE THE TABLE ITSELF. DESTROY THE TABLE