-- HOW TO CREATE A TABLE?
CREATE TABLE TEST_TABLE1		-- THIS TABLE DATA IS STORED IN "PRIMARY"
(
COL1 INTCOL2 INT
)

INSERT INTO TEST_TABLE1 VALUES (1,1),(2,2),(3,3)

SELECT * FROM TEST_TABLE1

-- HOW TO STORE TABLE DATA IN A SPECIFIC LOCATION (FILE)?
-- FOR THIS, WE NEED TO USE THE FILEGROUPS CREATED EARLIER.
CREATE TABLE ACCOUNTS_TABLE
(
ACC_ID INT, ACC_TYPE VARCHAR(3), ACC_BAL FLOAT
) ON FG_ACCOUNTS

INSERT INTO ACCOUNTS_TABLE VALUES (1001, 'SB', 875875)