/*
TEMPORARY TABLE:
	ALSO CALLED "TEMP TABLES"
	THESE ARE USED TO STORE TABLES ON A TEMPORARY BASIS.  

	THESE TEMPORARY TABLES ARE AUTO STORED IN "TEMPDB". TEMPDB IS ONE OF THE SYSTEM DATABASES.
	
	WHEN TO USE :	 WE USE TEMPDB FOR STORING ANY TYPE OF TEMPORARY DATA FOR CALCULATIONS.

	TYPES OF TEMPORARY TABLES:
		1. LOCAL TEMPORARY TABLES	:	ACCESSIBLE WITHIN THE SESSION (QUERY WINDOW)			# PREFIX
		2. GLOBAL TEMPORARY TABLES	:	ACCESSIBLE WITHIN THE SERVER (ALL QUERY CONNECTIONS)	## PREFIX
*/

CREATE TABLE #TABLE1 (COL1 INT, COL2 INT)			-- THIS IS A LOCAL  TEMPORARY TABLE
INSERT INTO #TABLE1 VALUES (1,1), (2,2), (3,3)
SELECT * FROM #TABLE1


CREATE TABLE ##TABLE2 (COL1 INT, COL2 INT)			-- THIS IS A GLOBAL TEMPORARY TABLE
INSERT INTO ##TABLE2 VALUES (100,100), (200,200), (300,300)
SELECT * FROM ##TABLE2


SELECT * FROM #TABLE1
SELECT * FROM ##TABLE2



