create table Reservation
(
Aircraft_Code varchar(10), 
No_of_Seats int, 
Class_Code varchar(10)
)

-- ITEM 1:	EXAMPLES FOR AUTOCOMMIT TRANSACTIONS. means AUTO SAVE.  
INSERT INTO Reservation VALUES ('AI21', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI22', 22, 'ECO')

-- ITEM 2:	EXAMPLES FOR EXPLICIT TRANSACTIONS
BEGIN TRANSACTION T1
INSERT INTO Reservation VALUES ('AI127', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI128', 22, 'ECO')
COMMIT

BEGIN TRANSACTION T2
INSERT INTO Reservation VALUES ('AI129', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI130', 22, 'ECO')
ROLLBACK

-- ITEM #3: 	EXAMPLE FOR IMPLICIT TRANSACTION
SET IMPLICIT_TRANSACTIONS ON			-- THIS SETTING IS AT SESSION LEVEL		
INSERT INTO Reservation VALUES ('AI131', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI132', 23, 'ECO')
COMMIT

SELECT * FROM Reservation

SET IMPLICIT_TRANSACTIONS OFF			-- THIS SETTING IS AT SESSION LEVEL. DEFAULT IS OFF.

/*
TEMPORARY TABLES	:	 THESE TABLES ARE STORED IN TEMPDB.  FOR EASIER ACCESS TO ANY TEMPORARY DATA.
TYPES OF TEMPORARY TABLES:
						1. LOCAL TEMPORARY TABLES	:	ACCESSIBLE WITHIN THE SESSION. PREFIX : #
						2. GLOBAL TEMPORARY TABLES	:	ACCESSIBLE ACROSS ALL SESSIONS. PREFIX : ##

*/

CREATE TABLE #TABLE1 (COL1 INT, COL2 INT)
CREATE TABLE ##TABLE2 (COL1 INT, COL2 INT)

INSERT INTO #TABLE1 VALUES (1,1),(2,2),(3,3)
INSERT INTO ##TABLE2 VALUES (11,11),(22,22),(33,33)

SELECT * FROM #TABLE1
SELECT * FROM ##TABLE2


-- IN OTHER SESSION WINDOW  [FILE > NEW > QUERY WITH CURRENT CONNECTION]
SELECT * FROM #TABLE1			-- ERROR; REASON : NOT ACESSIBLE. LOCAL TEMP TABLE
SELECT * FROM ##TABLE2			-- NO ERROR; ACCESSIBLE ACROSS ALL SESSIONS. GLOBAL
