CREATE TABLE EMP_INFO			
(
EMP_ID	 INT,	EMP_FNAME	VARCHAR (30),	 EMP_CNTRY	CHAR(50), EMP_SAL	BIGINT		
)						
INSERT 	  EMP_INFO VALUES  (1001, 'AMIN',  'CANADA', 45678) , ('1002', 'JOHN', 'CANADA', 643643)	
INSERT   EMP_INFO VALUES   (1003, 'SAI', 'INDIA', 36363), (1004, 'SAISHA', 'INDIA',20000)		
INSERT   EMP_INFO VALUES   (1005, 'SAISH', 'INDIA', 43643),   (1006, 'ADAM', 'USA', NULL)   
SELECT * FROM EMPLOYEE_INFO 

-- EXAMPLE 1:  USER DEFINED VIEWS 
CREATE VIEW VW_INDIA_EMPLOYEES
AS
SELECT * FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'INDIA'

-- TO ACCESS ABOVE VIEW
SELECT * FROM VW_INDIA_EMPLOYEES

-- IMPORTANT SYSTEM VIEWS : FOR METADATA [SYSTEM INFORMATION] AUDITS
SELECT * FROM SYS.DATABASES		-- TO REPORT LIST OF ALL DATABASES IN THE SERVER
SELECT * FROM SYS.SCHEMAS		-- TO REPORT LIST OF ALL SCHEMAS IN THE DATABASE
SELECT * FROM SYS.TABLES		-- TO REPORT LIST OF ALL TABLES IN THE DATABASE
SELECT * FROM SYS.INDEXES		-- TO REPORT LIST OF ALL INDEXES IN THE DATABASE
SELECT * FROM SYS.OBJECTS		-- TO REPORT LIST OF ALL OBJECTS IN THE DATABASE
